FROM node:18-alpine

WORKDIR /app

COPY src/admin-server.js ./src/
COPY admin-panel ./admin-panel
COPY package*.json ./

RUN npm ci --only=production

USER node

EXPOSE 3001

CMD ["node", "src/admin-server.js"]
